### ISSUE TITLE
Complete workshop 5 content

### ISSUE THREAD

**Issue by mitchelloharawild** [Jiaying-Wu/R-Workshops-for-Beginners#10]
## Background info
Audience: New R users assuming only prior experience from earlier workshops.
Content: Data analysis and tidying with `tidyr`, `dplyr`, and `stringr`.
Duration: 1 hour

## Structure
1. Complete survey as people come in (perhaps in a title slide/page)
1. Getting started - what is tidy data with `tidyr`?
1. Getting started - manipulating data with `dplyr`?
1. Getting started - working with strings with `stringr`?
1. Your turn - analyse survey data

**Comment by Jiaying-Wu** [comment]
This structure looks good!

**Comment by Jiaying-Wu** [comment]
Hello @mitchelloharawild ,

I have add the section "Analyse survey data" into the slide. It contain the instruction to download the survey description and survey data.

Also i have prepare the incomplete html code for survey data:

`<a href="workshop5/data/survey_data.csv" download="survey_data.csv"></a>Survey data`

Once the audiences complete the survey, i will download it as csv file and upload into GitHub and change the code as:

`<a href="workshop5/data/survey_data.csv" download="survey_data.csv">Survey data</a>`

It should be able to finish in few minutes.

Can you please have a look, then finalise the material of workshop 5 and upload into the sever?

Thank you!

Cheers

**Comment by mitchelloharawild** [comment]
Great, thanks. I'll be adding more content tomorrow using the above structure.
Looking forward to the workshop, should be good I think.

**Comment by mitchelloharawild** [comment]
## Refined structure

#### Welcome
* Complete survey (provide link/qr)
* Overview/goals

#### Getting started - what is tidy data with tidyr?
* Examples of (un)tidy data
* What is tidy data?
* Making data tidy
* `gather()`/`spread()` (`pivot_longer()`/`pivot_wider()`)
* `separate()`/`unite()`
* `nest()`/`unnest()`

#### Getting started - manipulating data with dplyr?
* `filter()`
* `select()`
* `rename()`
* `mutate()`
* `summarise()`
* `group_by()`
* `distinct()`/`count()`/`tally()` - are they necessary?

#### Getting started - working with strings with stringr?
* The problem with text
* Functions for working with text from `stringr`
* Regular expressions :scream: 

#### Your turn - analyse survey data
Some plots / analysis of the survey data.

**Comment by Jiaying-Wu** [comment]
@mitchelloharawild 
It looks great. Can you please update to the Github and publish it once you finalise?

**Comment by mitchelloharawild** [comment]
Yep, will do. Thanks.

**Comment by mitchelloharawild** [comment]
FYI  the slides are fixed to echo all code.
Thanks for organising this workshop!
