### ISSUE TITLE
Reload material of workshop 2 to sever

### ISSUE THREAD

**Issue by Jiaying-Wu** [Jiaying-Wu/R-Workshops-for-Beginners#7]
I have commit the change to the Rmd of workshop 2 - Introduction to R Markdown.

Included add  new preferred name of Helper, and delete image of markdown language tutorial. And move it to the Resources section.

Can you please upload the latest version of Rmd file to the sever?

[link file](https://github.com/Jiaying-Wu/R-Workshops-for-Beginners/blob/master/workshop2/workshop2_rmarkdown.Rmd)

**Comment by mitchelloharawild** [comment]
@dicook Can you upload this? I've tried a couple of times and it is giving me an out of memory error in the logs:

> 2019-08-15T07:01:34.477788+00:00 shinyapps[system]: Out of memory!

**Comment by mitchelloharawild** [comment]
Never mind, I've upgraded the instance to include more RAM and it seems to be okay now.
Deployed! :+1:
